name: CI Workflow
on: [push]

jobs:
  generate-apk:
    name: Generate Apk
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Generate apk
        run: ./gradlew assembleDebug
      - name: Upload Apk
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: app/build/outputs/apk/debug/app-debug.apk
