# 1
name: CI Workflow
# 2
on: [push]

# 3
jobs:
  build-and-test:
    # 4
    name: Build and run tests
    # 5
    runs-on: macos-latest
    # 6
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Print contents in current directory
        run: ls -la
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          avd-name: test
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: app/build/reports
